export type Azienda = {
  id: string;
  nome: string;
  description: string;
  utili?: number;
  isProfitable: boolean;
};

export const aziendeIniziali = [
  {
    id: "1",
    nome: "Apple",
    ticker: "AAPL",
    description: "Azienda tecnologica",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: 1000,
    isProfitable: true,
  },
  {
    id: "2",
    nome: "Microsoft",
    ticker: "MSFT",
    description: "Azienda di software",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: 2000,
    isProfitable: true,
  },
  {
    id: "3",
    nome: "Alphabet",
    ticker: "GOOGL",
    description: "Azienda di ricerca e pubblicità",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: -3000,
    isProfitable: true,
  },
  {
    id: "4",
    nome: "Amazon.com",
    ticker: "AMZN",
    description: "Azienda di e-commerce",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: 4000,
    isProfitable: true,
  },
  {
    id: "5",
    nome: "Tesla",
    ticker: "TSLA",
    description: "Azienda automobilistica elettrica",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: 5000,
    isProfitable: true,
  },
  {
    id: "6",
    nome: "Facebook",
    ticker: "FB",
    description: "Azienda di social media",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: -6000,
    isProfitable: true,
  },
  {
    id: "7",
    nome: "Netflix",
    ticker: "NFLX",
    description: "Azienda di streaming video",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: 7000,
    isProfitable: true,
  },
  {
    id: "8",
    nome: "Samsung",
    ticker: "SMSG",
    description: "Azienda di elettronica",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: 8000,
    isProfitable: true,
  },
  {
    id: "9",
    nome: "Sony",
    ticker: "SONY",
    description: "Azienda di elettronica e intrattenimento",
    azioniPossedute: 200,
    prezzo: "28€",
    utili: 9000,
    isProfitable: true,
  },
];
