import { StyleSheet } from "react-native";

const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(30, 41, 59, 0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    backgroundColor: "#f8fafc",
    padding: 28,
    borderRadius: 20,
    minWidth: 320,
    maxWidth: 420,
    width: "92%",
    alignItems: "stretch",
    boxShadow: "0px 4px 16px rgba(0,0,0,0.1)",
    elevation: 30,
    maxHeight: "85%",
  },
  modalTitle: {
    fontWeight: "700",
    fontSize: 22,
    marginBottom: 18,
    textAlign: "center",
    color: "#1e293b",
    letterSpacing: 0.5,
  },
  modalSection: {
    marginBottom: 18,
    alignItems: "flex-start",
    width: "100%",
    backgroundColor: "#e0e7ef",
    borderRadius: 10,
    padding: 14,
  },
  modalButton: {
    backgroundColor: "#2563eb",
    paddingVertical: 14,
    paddingHorizontal: 0,
    borderRadius: 10,
    alignItems: "center",
    marginHorizontal: 4,
    marginTop: 0,
    boxShadow: "0px 2px 4px rgba(37,99,235,0.1)",
    elevation: 2,
    minWidth: 120,
    flexGrow: 1,
  },
  modalButtonRed: {
    backgroundColor: "#ef4444",
    shadowColor: "#ef4444",
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginTop: 24,
    width: "100%",
  },
  closeButton: {
    marginTop: 18,
    backgroundColor: "#ef4444",
    padding: 12,
    borderRadius: 8,
    alignSelf: "center",
    minWidth: 100,
    alignItems: "center",
  },
});

export default modalStyles;
