import { StyleSheet } from "react-native";

const addNewCompanyStyles = StyleSheet.create({
  scrollContent: {
    paddingBottom: 40,
    width: "100%",
    alignItems: "center",
    backgroundColor: "#f8fafc",
  },
  header: {
    alignItems: "center",
    paddingTop: 32,
    paddingHorizontal: 8,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    width: "100%",
    backgroundColor: "#f1f5f9",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  headerIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#e0f2fe",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  iconText: {
    fontSize: 32,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: 6,
    letterSpacing: 0.2,
  },
  subtitle: {
    fontSize: 15,
    color: "#64748b",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 2,
  },
  textArea: {
    minHeight: 80,
    paddingTop: 16,
    textAlignVertical: "top",
    backgroundColor: "#f1f5f9",
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    color: "#1e293b",
   
  },
  buttonContainer: {
    width: "100%",
    paddingHorizontal: 0,
    paddingTop: 32,
    gap: 12,
    alignItems: "center",
  },
  primaryButton: {
    backgroundColor: "#2563eb",
    height: 52,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 6,
    width: "92%",
    maxWidth: 340,
    alignSelf: "center",
    flexDirection: "column",
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  secondaryButton: {
    backgroundColor: "#f1f5f9",
    height: 52,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#e5e7eb",
    width: "92%",
    maxWidth: 340,
    alignSelf: "center",
  },
  secondaryButtonText: {
    color: "#2563eb",
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  buttonRow: {
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
    marginTop: 28,
    width: "100%",
    paddingHorizontal: 8,
  },
});

export default addNewCompanyStyles;
